on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        profiles: [Release, Debug]
        compiler_ver: [9,10,11]
        standard: [17]

        queue: [
          -DUSE_CAF_LOCKFREE_QUEUE=ON,
          -DUSE_MOODYCAMEL_LOCKFREE_QUEUE=ON,
          -DUSE_SIMPLE_QUEUE=ON 
        ]

    steps:
      - uses: actions/checkout@v2

      - name: Install compiler
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y ninja-build gcc-${{ matrix.compiler_ver}} g++-${{ matrix.compiler_ver}} python3-pip python3 python3-dev python3-setuptools
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${{ matrix.compiler_ver}} 60 --slave /usr/bin/g++ g++ /usr/bin/g++-${{ matrix.compiler_ver}}
          pip3 install --no-cache-dir conan==1.40.3 cmake

      - name: Install conan dependencies
        run: |
          conan profile new default --detect
          conan profile update settings.compiler=gcc default
          conan profile update settings.compiler.version=${{matrix.compiler_ver}} default
          conan profile update env.CXX=g++-${{matrix.compiler_ver}} default
          conan profile update env.CC=gcc-${{matrix.compiler_ver}} default
          mkdir -p ${{github.workspace}}/build
          conan install ${{github.workspace}}/build/.. -if ${{github.workspace}}/build --build=missing -s build_type=Release

      - name: Configure CMake
        env:
          CC: gcc-${{ matrix.compiler_ver}}
          CXX: g++-${{ matrix.compiler_ver}}
          BUILD_TYPE: ${{ matrix.profiles }}
        run: cmake -B ${{github.workspace}}/build -GNinja -DCMAKE_BUILD_TYPE=${{ matrix.profiles }} -DCMAKE_CXX_STANDARD=${{ matrix.standard}} -DALLOW_EXAMPLES=ON -DALLOW_TESTS=ON ${{matrix.queue}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{ matrix.profiles }}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
      
