on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        package: [
          clang-7, clang-8, clang-9, clang-10
        ]

        compiler_ver: [
          7, 8, 9, 10
        ]

        build_type: [ Release, Debug ]

        standard: [17]

    steps:
      - uses: actions/checkout@v2

      - name: Install compiler
        run: |
          sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
          sudo apt-get update
          sudo apt-get install ninja-build ${{ matrix.package}} python3-pip python3 python3-dev python3-setuptools
          pip3 install --no-cache-dir conan==1.40.3

      - name: Install conan dependencies
        run: |
          conan profile new default --detect
          conan profile update settings.compiler=clang default
          conan profile update settings.compiler.version=${{ matrix.compiler_ver }} default
          conan profile update env.CXX=clang++-${{ matrix.compiler_ver}} default
          conan profile update env.CC=clang-${{ matrix.compiler_ver}} default
          mkdir -p ${{github.workspace}}/build
          conan install ${{github.workspace}}/build/.. -if ${{github.workspace}}/build --build=missing -s build_type=Release

      - name: Configure CMake
        env:
          CXX: clang++-${{ matrix.compiler_ver}}
          CC: clang-${{ matrix.compiler_ver}}
        run: cmake -B ${{github.workspace}}/build -GNinja -DCMAKE_BUILD_TYPE=${{ matrix.build_type}} -DCMAKE_CXX_STANDARD=${{ matrix.standard}} -DALLOW_EXAMPLES=ON -DALLOW_TESTS=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{ matrix.build_type}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}
      
